# Generated by Django 3.2.15 on 2022-08-19 19:14

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('district_slug', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eponym_core_data_added', models.BooleanField()),
                ('entry_complete', models.BooleanField()),
                ('map_link', models.URLField()),
                ('name', models.CharField(max_length=50)),
                ('street_slug', models.CharField(blank=True, max_length=50, null=True)),
                ('eponym_name', models.CharField(max_length=60)),
                ('eponym_date_of_birth', models.DateField(blank=True, null=True)),
                ('eponym_date_of_death', models.DateField(blank=True, null=True)),
                ('eponym_place_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('eponym_place_of_death', models.CharField(blank=True, max_length=50, null=True)),
                ('eponym_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='streets.district')),
            ],
        ),
    ]
