# Generated by Django 3.2.15 on 2022-11-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='image_available',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='street',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
