# Generated by Django 3.2.13 on 2022-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('people', models.ManyToManyField(blank=True, related_name='category_or_categories', to='streets.Person')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
