# Generated by Django 3.2.9 on 2021-11-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="street",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="street",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
