# Generated by Django 3.2.15 on 2023-06-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_image_path',
        ),
    ]
