# Generated by Django 3.2.9 on 2021-11-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("streets", "0002_alter_latitude_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="street",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streets",
                to="streets.district",
            ),
        ),
    ]
