# Generated by Django 3.2.15 on 2023-06-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0002_remove_district_district_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='district_image_path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
