# Generated by Django 3.2.13 on 2022-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='people',
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='people', to='streets.Category'),
        ),
    ]
