# Generated by Django 3.2.13 on 2022-05-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0003_auto_20220506_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='category',
        ),
        migrations.RemoveField(
            model_name='street',
            name='eponym',
        ),
        migrations.AddField(
            model_name='street',
            name='entry_complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='street',
            name='eponym_core_data_added',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='street',
            name='eponym_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='eponym_date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='eponym_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='eponym_name',
            field=models.CharField(default='eponym', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='street',
            name='eponym_place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='eponym_place_of_death',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
