# Generated by Django 3.2.15 on 2023-06-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0003_district_district_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_image_path',
        ),
    ]
