# Generated by Django 3.2.9 on 2021-11-11 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("streets", "0003_alter_street_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("name", models.CharField(max_length=60)),
                (
                    "street",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="streets.street",
                    ),
                ),
            ],
        ),
    ]
