# Generated by Django 3.2.15 on 2022-08-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0003_auto_20220830_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
