# Generated by Django 3.2.9 on 2021-11-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streets", "0004_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
    ]
