# Generated by Django 3.2.13 on 2022-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0004_auto_20220507_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='latitude',
        ),
        migrations.AddField(
            model_name='street',
            name='map_link',
            field=models.URLField(default='https://openstreetmap.org'),
            preserve_default=False,
        ),
    ]
