# Generated by Django 3.2.13 on 2022-05-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0005_auto_20220507_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='longitude',
        ),
    ]
