# Generated by Django 3.2.9 on 2021-11-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streets", "0006_auto_20211111_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="place_of_death",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
