# Generated by Django 3.2.9 on 2021-11-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streets", "0007_person_place_of_death"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="complete",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
