# Generated by Django 3.2.9 on 2021-11-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streets", "0008_person_complete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="complete",
            new_name="core_data_added",
        ),
        migrations.AddField(
            model_name="person",
            name="entry_complete",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
