# Generated by Django 3.2.20 on 2023-08-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streets", "0008_auto_20230802_1850"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="street",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="street",
            name="longitude",
        ),
    ]
