# Generated by Django 3.2.9 on 2022-01-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streets", "0009_auto_20211111_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="slug",
            field=models.CharField(
                default=models.CharField(max_length=50), max_length=50
            ),
        ),
        migrations.AddField(
            model_name="street",
            name="slug",
            field=models.CharField(
                default=models.CharField(max_length=50), max_length=50
            ),
        ),
    ]
