# Generated by Django 3.2.12 on 2022-02-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("streets", "0011_auto_20220202_2057"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
