# Generated by Django 3.2.13 on 2022-04-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0012_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
