# Generated by Django 3.2.13 on 2022-04-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0013_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='people',
            field=models.ManyToManyField(to='streets.Person'),
        ),
    ]
