# Generated by Django 3.2.13 on 2022-04-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0014_auto_20220423_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='people',
            field=models.ManyToManyField(related_name='category_or_categories', to='streets.Person'),
        ),
    ]
