# Generated by Django 3.2.13 on 2022-04-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0015_alter_category_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_or_categories', to='streets.Person'),
        ),
    ]
