# Generated by Django 4.2 on 2025-01-05 20:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("body", tinymce.models.HTMLField(blank=True, null=True)),
                ("slug", models.CharField(max_length=50)),
            ],
        ),
    ]
