# Generated by Django 3.2.19 on 2023-06-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='ready_to_publish',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
