# Generated by Django 3.2.19 on 2023-06-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpost_ready_to_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="published",
            field=models.DateField(blank=True, null=True),
        ),
    ]
