# Generated by Django 3.2.15 on 2022-08-27 19:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
